<Project>

  <PropertyGroup>
    <NetVersion>net10.0</NetVersion>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectName)' != 'PrayerTimeEngine.MAUI'">
    <TargetFramework>$(NetVersion)</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'PrayerTimeEngine.MAUI'">
    <TargetFrameworks>$(NetVersion)-android;$(NetVersion)-ios</TargetFrameworks>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">26.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.22000.0</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.22000.0</TargetPlatformMinVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'PrayerTimeEngine.MAUI' And $([MSBuild]::IsOSPlatform('maccatalyst'))">
    <TargetFrameworks>$(TargetFrameworks);$(NetVersion)-maccatalyst</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'PrayerTimeEngine.MAUI' And $([MSBuild]::IsOSPlatform('windows'))">
    <TargetFrameworks>$(TargetFrameworks);$(NetVersion)-windows10.0.26100.0</TargetFrameworks>
  </PropertyGroup>

</Project>
