// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;

#pragma warning disable 219, 612, 618
#nullable disable

namespace PrayerTimeEngine.Core.Data.EntityFramework
{
    public partial class AppDbContextModel
    {
        partial void Initialize()
        {
            var faziletCity = FaziletCityEntityType.Create(this);
            var faziletCountry = FaziletCountryEntityType.Create(this);
            var faziletPrayerTimes = FaziletPrayerTimesEntityType.Create(this);
            var muwaqqitPrayerTimes = MuwaqqitPrayerTimesEntityType.Create(this);
            var semerkandCity = SemerkandCityEntityType.Create(this);
            var semerkandCountry = SemerkandCountryEntityType.Create(this);
            var semerkandPrayerTimes = SemerkandPrayerTimesEntityType.Create(this);
            var profile = ProfileEntityType.Create(this);
            var profileLocationConfig = ProfileLocationConfigEntityType.Create(this);
            var profileTimeConfig = ProfileTimeConfigEntityType.Create(this);

            FaziletCityEntityType.CreateForeignKey1(faziletCity, faziletCountry);
            SemerkandCityEntityType.CreateForeignKey1(semerkandCity, semerkandCountry);
            ProfileLocationConfigEntityType.CreateForeignKey1(profileLocationConfig, profile);
            ProfileTimeConfigEntityType.CreateForeignKey1(profileTimeConfig, profile);

            FaziletCityEntityType.CreateAnnotations(faziletCity);
            FaziletCountryEntityType.CreateAnnotations(faziletCountry);
            FaziletPrayerTimesEntityType.CreateAnnotations(faziletPrayerTimes);
            MuwaqqitPrayerTimesEntityType.CreateAnnotations(muwaqqitPrayerTimes);
            SemerkandCityEntityType.CreateAnnotations(semerkandCity);
            SemerkandCountryEntityType.CreateAnnotations(semerkandCountry);
            SemerkandPrayerTimesEntityType.CreateAnnotations(semerkandPrayerTimes);
            ProfileEntityType.CreateAnnotations(profile);
            ProfileLocationConfigEntityType.CreateAnnotations(profileLocationConfig);
            ProfileTimeConfigEntityType.CreateAnnotations(profileTimeConfig);

            AddAnnotation("ProductVersion", "8.0.0");
            AddRuntimeAnnotation("Relational:RelationalModel", CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var faziletCity = FindEntityType("PrayerTimeEngine.Core.Domain.Calculators.Fazilet.Models.FaziletCity")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            faziletCity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCityTableBase = new TableBase("PrayerTimeEngine.Core.Domain.Calculators.Fazilet.Models.FaziletCity", null, relationalModel);
            var countryIDColumnBase = new ColumnBase<ColumnMappingBase>("CountryID", "INTEGER", prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCityTableBase);
            prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCityTableBase.Columns.Add("CountryID", countryIDColumnBase);
            var iDColumnBase = new ColumnBase<ColumnMappingBase>("ID", "INTEGER", prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCityTableBase);
            prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCityTableBase.Columns.Add("ID", iDColumnBase);
            var nameColumnBase = new ColumnBase<ColumnMappingBase>("Name", "TEXT", prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCityTableBase)
            {
                IsNullable = true
            };
            prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCityTableBase.Columns.Add("Name", nameColumnBase);
            relationalModel.DefaultTables.Add("PrayerTimeEngine.Core.Domain.Calculators.Fazilet.Models.FaziletCity", prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCityTableBase);
            var prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCityMappingBase = new TableMappingBase<ColumnMappingBase>(faziletCity, prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCityTableBase, true);
            prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCityTableBase.AddTypeMapping(prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCityMappingBase, false);
            defaultTableMappings.Add(prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)iDColumnBase, faziletCity.FindProperty("ID")!, prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)countryIDColumnBase, faziletCity.FindProperty("CountryID")!, prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase, faziletCity.FindProperty("Name")!, prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCityMappingBase);

            var tableMappings = new List<TableMapping>();
            faziletCity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var faziletCitiesTable = new Table("FaziletCities", null, relationalModel);
            var iDColumn = new Column("ID", "INTEGER", faziletCitiesTable);
            faziletCitiesTable.Columns.Add("ID", iDColumn);
            var countryIDColumn = new Column("CountryID", "INTEGER", faziletCitiesTable);
            faziletCitiesTable.Columns.Add("CountryID", countryIDColumn);
            var nameColumn = new Column("Name", "TEXT", faziletCitiesTable)
            {
                IsNullable = true
            };
            faziletCitiesTable.Columns.Add("Name", nameColumn);
            var pK_FaziletCities = new UniqueConstraint("PK_FaziletCities", faziletCitiesTable, new[] { iDColumn });
            faziletCitiesTable.PrimaryKey = pK_FaziletCities;
            var pK_FaziletCitiesUc = RelationalModel.GetKey(this,
                "PrayerTimeEngine.Core.Domain.Calculators.Fazilet.Models.FaziletCity",
                new[] { "ID" });
            pK_FaziletCities.MappedKeys.Add(pK_FaziletCitiesUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_FaziletCitiesUc).Add(pK_FaziletCities);
            faziletCitiesTable.UniqueConstraints.Add("PK_FaziletCities", pK_FaziletCities);
            var iX_FaziletCities_CountryID = new TableIndex(
            "IX_FaziletCities_CountryID", faziletCitiesTable, new[] { countryIDColumn }, false);
            var iX_FaziletCities_CountryIDIx = RelationalModel.GetIndex(this,
                "PrayerTimeEngine.Core.Domain.Calculators.Fazilet.Models.FaziletCity",
                new[] { "CountryID" });
            iX_FaziletCities_CountryID.MappedIndexes.Add(iX_FaziletCities_CountryIDIx);
            RelationalModel.GetOrCreateTableIndexes(iX_FaziletCities_CountryIDIx).Add(iX_FaziletCities_CountryID);
            faziletCitiesTable.Indexes.Add("IX_FaziletCities_CountryID", iX_FaziletCities_CountryID);
            relationalModel.Tables.Add(("FaziletCities", null), faziletCitiesTable);
            var faziletCitiesTableMapping = new TableMapping(faziletCity, faziletCitiesTable, true);
            faziletCitiesTable.AddTypeMapping(faziletCitiesTableMapping, false);
            tableMappings.Add(faziletCitiesTableMapping);
            RelationalModel.CreateColumnMapping(iDColumn, faziletCity.FindProperty("ID")!, faziletCitiesTableMapping);
            RelationalModel.CreateColumnMapping(countryIDColumn, faziletCity.FindProperty("CountryID")!, faziletCitiesTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn, faziletCity.FindProperty("Name")!, faziletCitiesTableMapping);

            var faziletCountry = FindEntityType("PrayerTimeEngine.Core.Domain.Calculators.Fazilet.Models.FaziletCountry")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            faziletCountry.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCountryTableBase = new TableBase("PrayerTimeEngine.Core.Domain.Calculators.Fazilet.Models.FaziletCountry", null, relationalModel);
            var iDColumnBase0 = new ColumnBase<ColumnMappingBase>("ID", "INTEGER", prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCountryTableBase);
            prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCountryTableBase.Columns.Add("ID", iDColumnBase0);
            var nameColumnBase0 = new ColumnBase<ColumnMappingBase>("Name", "TEXT", prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCountryTableBase)
            {
                IsNullable = true
            };
            prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCountryTableBase.Columns.Add("Name", nameColumnBase0);
            relationalModel.DefaultTables.Add("PrayerTimeEngine.Core.Domain.Calculators.Fazilet.Models.FaziletCountry", prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCountryTableBase);
            var prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCountryMappingBase = new TableMappingBase<ColumnMappingBase>(faziletCountry, prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCountryTableBase, true);
            prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCountryTableBase.AddTypeMapping(prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCountryMappingBase, false);
            defaultTableMappings0.Add(prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCountryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)iDColumnBase0, faziletCountry.FindProperty("ID")!, prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCountryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase0, faziletCountry.FindProperty("Name")!, prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletCountryMappingBase);

            var tableMappings0 = new List<TableMapping>();
            faziletCountry.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var faziletCountriesTable = new Table("FaziletCountries", null, relationalModel);
            var iDColumn0 = new Column("ID", "INTEGER", faziletCountriesTable);
            faziletCountriesTable.Columns.Add("ID", iDColumn0);
            var nameColumn0 = new Column("Name", "TEXT", faziletCountriesTable)
            {
                IsNullable = true
            };
            faziletCountriesTable.Columns.Add("Name", nameColumn0);
            var pK_FaziletCountries = new UniqueConstraint("PK_FaziletCountries", faziletCountriesTable, new[] { iDColumn0 });
            faziletCountriesTable.PrimaryKey = pK_FaziletCountries;
            var pK_FaziletCountriesUc = RelationalModel.GetKey(this,
                "PrayerTimeEngine.Core.Domain.Calculators.Fazilet.Models.FaziletCountry",
                new[] { "ID" });
            pK_FaziletCountries.MappedKeys.Add(pK_FaziletCountriesUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_FaziletCountriesUc).Add(pK_FaziletCountries);
            faziletCountriesTable.UniqueConstraints.Add("PK_FaziletCountries", pK_FaziletCountries);
            relationalModel.Tables.Add(("FaziletCountries", null), faziletCountriesTable);
            var faziletCountriesTableMapping = new TableMapping(faziletCountry, faziletCountriesTable, true);
            faziletCountriesTable.AddTypeMapping(faziletCountriesTableMapping, false);
            tableMappings0.Add(faziletCountriesTableMapping);
            RelationalModel.CreateColumnMapping(iDColumn0, faziletCountry.FindProperty("ID")!, faziletCountriesTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn0, faziletCountry.FindProperty("Name")!, faziletCountriesTableMapping);

            var faziletPrayerTimes = FindEntityType("PrayerTimeEngine.Core.Domain.Calculators.Fazilet.Models.FaziletPrayerTimes")!;

            var defaultTableMappings1 = new List<TableMappingBase<ColumnMappingBase>>();
            faziletPrayerTimes.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings1);
            var prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase = new TableBase("PrayerTimeEngine.Core.Domain.Calculators.Fazilet.Models.FaziletPrayerTimes", null, relationalModel);
            var asrColumnBase = new ColumnBase<ColumnMappingBase>("Asr", "TEXT", prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase.Columns.Add("Asr", asrColumnBase);
            var cityIDColumnBase = new ColumnBase<ColumnMappingBase>("CityID", "INTEGER", prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase.Columns.Add("CityID", cityIDColumnBase);
            var dateColumnBase = new ColumnBase<ColumnMappingBase>("Date", "TEXT", prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase.Columns.Add("Date", dateColumnBase);
            var dhuhrColumnBase = new ColumnBase<ColumnMappingBase>("Dhuhr", "TEXT", prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase.Columns.Add("Dhuhr", dhuhrColumnBase);
            var fajrColumnBase = new ColumnBase<ColumnMappingBase>("Fajr", "TEXT", prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase.Columns.Add("Fajr", fajrColumnBase);
            var iDColumnBase1 = new ColumnBase<ColumnMappingBase>("ID", "INTEGER", prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase.Columns.Add("ID", iDColumnBase1);
            var imsakColumnBase = new ColumnBase<ColumnMappingBase>("Imsak", "TEXT", prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase.Columns.Add("Imsak", imsakColumnBase);
            var ishaColumnBase = new ColumnBase<ColumnMappingBase>("Isha", "TEXT", prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase.Columns.Add("Isha", ishaColumnBase);
            var maghribColumnBase = new ColumnBase<ColumnMappingBase>("Maghrib", "TEXT", prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase.Columns.Add("Maghrib", maghribColumnBase);
            var nextFajrColumnBase = new ColumnBase<ColumnMappingBase>("NextFajr", "TEXT", prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase)
            {
                IsNullable = true
            };
            prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase.Columns.Add("NextFajr", nextFajrColumnBase);
            var shuruqColumnBase = new ColumnBase<ColumnMappingBase>("Shuruq", "TEXT", prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase.Columns.Add("Shuruq", shuruqColumnBase);
            relationalModel.DefaultTables.Add("PrayerTimeEngine.Core.Domain.Calculators.Fazilet.Models.FaziletPrayerTimes", prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase);
            var prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesMappingBase = new TableMappingBase<ColumnMappingBase>(faziletPrayerTimes, prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase, true);
            prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesTableBase.AddTypeMapping(prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesMappingBase, false);
            defaultTableMappings1.Add(prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)iDColumnBase1, faziletPrayerTimes.FindProperty("ID")!, prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)asrColumnBase, faziletPrayerTimes.FindProperty("Asr")!, prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)cityIDColumnBase, faziletPrayerTimes.FindProperty("CityID")!, prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)dateColumnBase, faziletPrayerTimes.FindProperty("Date")!, prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)dhuhrColumnBase, faziletPrayerTimes.FindProperty("Dhuhr")!, prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)fajrColumnBase, faziletPrayerTimes.FindProperty("Fajr")!, prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)imsakColumnBase, faziletPrayerTimes.FindProperty("Imsak")!, prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)ishaColumnBase, faziletPrayerTimes.FindProperty("Isha")!, prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)maghribColumnBase, faziletPrayerTimes.FindProperty("Maghrib")!, prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nextFajrColumnBase, faziletPrayerTimes.FindProperty("NextFajr")!, prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)shuruqColumnBase, faziletPrayerTimes.FindProperty("Shuruq")!, prayerTimeEngineCoreDomainCalculatorsFaziletModelsFaziletPrayerTimesMappingBase);

            var tableMappings1 = new List<TableMapping>();
            faziletPrayerTimes.SetRuntimeAnnotation("Relational:TableMappings", tableMappings1);
            var faziletPrayerTimesTable = new Table("FaziletPrayerTimes", null, relationalModel);
            var iDColumn1 = new Column("ID", "INTEGER", faziletPrayerTimesTable);
            faziletPrayerTimesTable.Columns.Add("ID", iDColumn1);
            var asrColumn = new Column("Asr", "TEXT", faziletPrayerTimesTable);
            faziletPrayerTimesTable.Columns.Add("Asr", asrColumn);
            var cityIDColumn = new Column("CityID", "INTEGER", faziletPrayerTimesTable);
            faziletPrayerTimesTable.Columns.Add("CityID", cityIDColumn);
            var dateColumn = new Column("Date", "TEXT", faziletPrayerTimesTable);
            faziletPrayerTimesTable.Columns.Add("Date", dateColumn);
            var dhuhrColumn = new Column("Dhuhr", "TEXT", faziletPrayerTimesTable);
            faziletPrayerTimesTable.Columns.Add("Dhuhr", dhuhrColumn);
            var fajrColumn = new Column("Fajr", "TEXT", faziletPrayerTimesTable);
            faziletPrayerTimesTable.Columns.Add("Fajr", fajrColumn);
            var imsakColumn = new Column("Imsak", "TEXT", faziletPrayerTimesTable);
            faziletPrayerTimesTable.Columns.Add("Imsak", imsakColumn);
            var ishaColumn = new Column("Isha", "TEXT", faziletPrayerTimesTable);
            faziletPrayerTimesTable.Columns.Add("Isha", ishaColumn);
            var maghribColumn = new Column("Maghrib", "TEXT", faziletPrayerTimesTable);
            faziletPrayerTimesTable.Columns.Add("Maghrib", maghribColumn);
            var nextFajrColumn = new Column("NextFajr", "TEXT", faziletPrayerTimesTable)
            {
                IsNullable = true
            };
            faziletPrayerTimesTable.Columns.Add("NextFajr", nextFajrColumn);
            var shuruqColumn = new Column("Shuruq", "TEXT", faziletPrayerTimesTable);
            faziletPrayerTimesTable.Columns.Add("Shuruq", shuruqColumn);
            var pK_FaziletPrayerTimes = new UniqueConstraint("PK_FaziletPrayerTimes", faziletPrayerTimesTable, new[] { iDColumn1 });
            faziletPrayerTimesTable.PrimaryKey = pK_FaziletPrayerTimes;
            var pK_FaziletPrayerTimesUc = RelationalModel.GetKey(this,
                "PrayerTimeEngine.Core.Domain.Calculators.Fazilet.Models.FaziletPrayerTimes",
                new[] { "ID" });
            pK_FaziletPrayerTimes.MappedKeys.Add(pK_FaziletPrayerTimesUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_FaziletPrayerTimesUc).Add(pK_FaziletPrayerTimes);
            faziletPrayerTimesTable.UniqueConstraints.Add("PK_FaziletPrayerTimes", pK_FaziletPrayerTimes);
            relationalModel.Tables.Add(("FaziletPrayerTimes", null), faziletPrayerTimesTable);
            var faziletPrayerTimesTableMapping = new TableMapping(faziletPrayerTimes, faziletPrayerTimesTable, true);
            faziletPrayerTimesTable.AddTypeMapping(faziletPrayerTimesTableMapping, false);
            tableMappings1.Add(faziletPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(iDColumn1, faziletPrayerTimes.FindProperty("ID")!, faziletPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(asrColumn, faziletPrayerTimes.FindProperty("Asr")!, faziletPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(cityIDColumn, faziletPrayerTimes.FindProperty("CityID")!, faziletPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(dateColumn, faziletPrayerTimes.FindProperty("Date")!, faziletPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(dhuhrColumn, faziletPrayerTimes.FindProperty("Dhuhr")!, faziletPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(fajrColumn, faziletPrayerTimes.FindProperty("Fajr")!, faziletPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(imsakColumn, faziletPrayerTimes.FindProperty("Imsak")!, faziletPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(ishaColumn, faziletPrayerTimes.FindProperty("Isha")!, faziletPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(maghribColumn, faziletPrayerTimes.FindProperty("Maghrib")!, faziletPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(nextFajrColumn, faziletPrayerTimes.FindProperty("NextFajr")!, faziletPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(shuruqColumn, faziletPrayerTimes.FindProperty("Shuruq")!, faziletPrayerTimesTableMapping);

            var muwaqqitPrayerTimes = FindEntityType("PrayerTimeEngine.Core.Domain.Calculators.Muwaqqit.Models.MuwaqqitPrayerTimes")!;

            var defaultTableMappings2 = new List<TableMappingBase<ColumnMappingBase>>();
            muwaqqitPrayerTimes.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings2);
            var prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase = new TableBase("PrayerTimeEngine.Core.Domain.Calculators.Muwaqqit.Models.MuwaqqitPrayerTimes", null, relationalModel);
            var asrColumnBase0 = new ColumnBase<ColumnMappingBase>("Asr", "TEXT", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.Columns.Add("Asr", asrColumnBase0);
            var asrKarahaColumnBase = new ColumnBase<ColumnMappingBase>("AsrKaraha", "TEXT", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.Columns.Add("AsrKaraha", asrKarahaColumnBase);
            var asrKarahaDegreeColumnBase = new ColumnBase<ColumnMappingBase>("AsrKarahaDegree", "REAL", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.Columns.Add("AsrKarahaDegree", asrKarahaDegreeColumnBase);
            var asrMithlaynColumnBase = new ColumnBase<ColumnMappingBase>("AsrMithlayn", "TEXT", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.Columns.Add("AsrMithlayn", asrMithlaynColumnBase);
            var dateColumnBase0 = new ColumnBase<ColumnMappingBase>("Date", "TEXT", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.Columns.Add("Date", dateColumnBase0);
            var dhuhrColumnBase0 = new ColumnBase<ColumnMappingBase>("Dhuhr", "TEXT", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.Columns.Add("Dhuhr", dhuhrColumnBase0);
            var duhaColumnBase = new ColumnBase<ColumnMappingBase>("Duha", "TEXT", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.Columns.Add("Duha", duhaColumnBase);
            var fajrColumnBase0 = new ColumnBase<ColumnMappingBase>("Fajr", "TEXT", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.Columns.Add("Fajr", fajrColumnBase0);
            var fajrDegreeColumnBase = new ColumnBase<ColumnMappingBase>("FajrDegree", "REAL", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.Columns.Add("FajrDegree", fajrDegreeColumnBase);
            var iDColumnBase2 = new ColumnBase<ColumnMappingBase>("ID", "INTEGER", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.Columns.Add("ID", iDColumnBase2);
            var insertInstantColumnBase = new ColumnBase<ColumnMappingBase>("InsertInstant", "TEXT", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase)
            {
                IsNullable = true
            };
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.Columns.Add("InsertInstant", insertInstantColumnBase);
            var ishaColumnBase0 = new ColumnBase<ColumnMappingBase>("Isha", "TEXT", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.Columns.Add("Isha", ishaColumnBase0);
            var ishaDegreeColumnBase = new ColumnBase<ColumnMappingBase>("IshaDegree", "REAL", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.Columns.Add("IshaDegree", ishaDegreeColumnBase);
            var ishtibaqColumnBase = new ColumnBase<ColumnMappingBase>("Ishtibaq", "TEXT", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.Columns.Add("Ishtibaq", ishtibaqColumnBase);
            var ishtibaqDegreeColumnBase = new ColumnBase<ColumnMappingBase>("IshtibaqDegree", "REAL", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.Columns.Add("IshtibaqDegree", ishtibaqDegreeColumnBase);
            var latitudeColumnBase = new ColumnBase<ColumnMappingBase>("Latitude", "TEXT", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.Columns.Add("Latitude", latitudeColumnBase);
            var longitudeColumnBase = new ColumnBase<ColumnMappingBase>("Longitude", "TEXT", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.Columns.Add("Longitude", longitudeColumnBase);
            var maghribColumnBase0 = new ColumnBase<ColumnMappingBase>("Maghrib", "TEXT", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.Columns.Add("Maghrib", maghribColumnBase0);
            var nextFajrColumnBase0 = new ColumnBase<ColumnMappingBase>("NextFajr", "TEXT", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.Columns.Add("NextFajr", nextFajrColumnBase0);
            var shuruqColumnBase0 = new ColumnBase<ColumnMappingBase>("Shuruq", "TEXT", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.Columns.Add("Shuruq", shuruqColumnBase0);
            relationalModel.DefaultTables.Add("PrayerTimeEngine.Core.Domain.Calculators.Muwaqqit.Models.MuwaqqitPrayerTimes", prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase);
            var prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase = new TableMappingBase<ColumnMappingBase>(muwaqqitPrayerTimes, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase, true);
            prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesTableBase.AddTypeMapping(prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase, false);
            defaultTableMappings2.Add(prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)iDColumnBase2, muwaqqitPrayerTimes.FindProperty("ID")!, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)asrColumnBase0, muwaqqitPrayerTimes.FindProperty("Asr")!, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)asrKarahaColumnBase, muwaqqitPrayerTimes.FindProperty("AsrKaraha")!, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)asrKarahaDegreeColumnBase, muwaqqitPrayerTimes.FindProperty("AsrKarahaDegree")!, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)asrMithlaynColumnBase, muwaqqitPrayerTimes.FindProperty("AsrMithlayn")!, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)dateColumnBase0, muwaqqitPrayerTimes.FindProperty("Date")!, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)dhuhrColumnBase0, muwaqqitPrayerTimes.FindProperty("Dhuhr")!, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)duhaColumnBase, muwaqqitPrayerTimes.FindProperty("Duha")!, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)fajrColumnBase0, muwaqqitPrayerTimes.FindProperty("Fajr")!, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)fajrDegreeColumnBase, muwaqqitPrayerTimes.FindProperty("FajrDegree")!, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)insertInstantColumnBase, muwaqqitPrayerTimes.FindProperty("InsertInstant")!, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)ishaColumnBase0, muwaqqitPrayerTimes.FindProperty("Isha")!, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)ishaDegreeColumnBase, muwaqqitPrayerTimes.FindProperty("IshaDegree")!, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)ishtibaqColumnBase, muwaqqitPrayerTimes.FindProperty("Ishtibaq")!, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)ishtibaqDegreeColumnBase, muwaqqitPrayerTimes.FindProperty("IshtibaqDegree")!, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)latitudeColumnBase, muwaqqitPrayerTimes.FindProperty("Latitude")!, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)longitudeColumnBase, muwaqqitPrayerTimes.FindProperty("Longitude")!, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)maghribColumnBase0, muwaqqitPrayerTimes.FindProperty("Maghrib")!, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nextFajrColumnBase0, muwaqqitPrayerTimes.FindProperty("NextFajr")!, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)shuruqColumnBase0, muwaqqitPrayerTimes.FindProperty("Shuruq")!, prayerTimeEngineCoreDomainCalculatorsMuwaqqitModelsMuwaqqitPrayerTimesMappingBase);

            var tableMappings2 = new List<TableMapping>();
            muwaqqitPrayerTimes.SetRuntimeAnnotation("Relational:TableMappings", tableMappings2);
            var muwaqqitPrayerTimesTable = new Table("MuwaqqitPrayerTimes", null, relationalModel);
            var iDColumn2 = new Column("ID", "INTEGER", muwaqqitPrayerTimesTable);
            muwaqqitPrayerTimesTable.Columns.Add("ID", iDColumn2);
            var asrColumn0 = new Column("Asr", "TEXT", muwaqqitPrayerTimesTable);
            muwaqqitPrayerTimesTable.Columns.Add("Asr", asrColumn0);
            var asrKarahaColumn = new Column("AsrKaraha", "TEXT", muwaqqitPrayerTimesTable);
            muwaqqitPrayerTimesTable.Columns.Add("AsrKaraha", asrKarahaColumn);
            var asrKarahaDegreeColumn = new Column("AsrKarahaDegree", "REAL", muwaqqitPrayerTimesTable);
            muwaqqitPrayerTimesTable.Columns.Add("AsrKarahaDegree", asrKarahaDegreeColumn);
            var asrMithlaynColumn = new Column("AsrMithlayn", "TEXT", muwaqqitPrayerTimesTable);
            muwaqqitPrayerTimesTable.Columns.Add("AsrMithlayn", asrMithlaynColumn);
            var dateColumn0 = new Column("Date", "TEXT", muwaqqitPrayerTimesTable);
            muwaqqitPrayerTimesTable.Columns.Add("Date", dateColumn0);
            var dhuhrColumn0 = new Column("Dhuhr", "TEXT", muwaqqitPrayerTimesTable);
            muwaqqitPrayerTimesTable.Columns.Add("Dhuhr", dhuhrColumn0);
            var duhaColumn = new Column("Duha", "TEXT", muwaqqitPrayerTimesTable);
            muwaqqitPrayerTimesTable.Columns.Add("Duha", duhaColumn);
            var fajrColumn0 = new Column("Fajr", "TEXT", muwaqqitPrayerTimesTable);
            muwaqqitPrayerTimesTable.Columns.Add("Fajr", fajrColumn0);
            var fajrDegreeColumn = new Column("FajrDegree", "REAL", muwaqqitPrayerTimesTable);
            muwaqqitPrayerTimesTable.Columns.Add("FajrDegree", fajrDegreeColumn);
            var insertInstantColumn = new Column("InsertInstant", "TEXT", muwaqqitPrayerTimesTable)
            {
                IsNullable = true
            };
            muwaqqitPrayerTimesTable.Columns.Add("InsertInstant", insertInstantColumn);
            var ishaColumn0 = new Column("Isha", "TEXT", muwaqqitPrayerTimesTable);
            muwaqqitPrayerTimesTable.Columns.Add("Isha", ishaColumn0);
            var ishaDegreeColumn = new Column("IshaDegree", "REAL", muwaqqitPrayerTimesTable);
            muwaqqitPrayerTimesTable.Columns.Add("IshaDegree", ishaDegreeColumn);
            var ishtibaqColumn = new Column("Ishtibaq", "TEXT", muwaqqitPrayerTimesTable);
            muwaqqitPrayerTimesTable.Columns.Add("Ishtibaq", ishtibaqColumn);
            var ishtibaqDegreeColumn = new Column("IshtibaqDegree", "REAL", muwaqqitPrayerTimesTable);
            muwaqqitPrayerTimesTable.Columns.Add("IshtibaqDegree", ishtibaqDegreeColumn);
            var latitudeColumn = new Column("Latitude", "TEXT", muwaqqitPrayerTimesTable);
            muwaqqitPrayerTimesTable.Columns.Add("Latitude", latitudeColumn);
            var longitudeColumn = new Column("Longitude", "TEXT", muwaqqitPrayerTimesTable);
            muwaqqitPrayerTimesTable.Columns.Add("Longitude", longitudeColumn);
            var maghribColumn0 = new Column("Maghrib", "TEXT", muwaqqitPrayerTimesTable);
            muwaqqitPrayerTimesTable.Columns.Add("Maghrib", maghribColumn0);
            var nextFajrColumn0 = new Column("NextFajr", "TEXT", muwaqqitPrayerTimesTable);
            muwaqqitPrayerTimesTable.Columns.Add("NextFajr", nextFajrColumn0);
            var shuruqColumn0 = new Column("Shuruq", "TEXT", muwaqqitPrayerTimesTable);
            muwaqqitPrayerTimesTable.Columns.Add("Shuruq", shuruqColumn0);
            var pK_MuwaqqitPrayerTimes = new UniqueConstraint("PK_MuwaqqitPrayerTimes", muwaqqitPrayerTimesTable, new[] { iDColumn2 });
            muwaqqitPrayerTimesTable.PrimaryKey = pK_MuwaqqitPrayerTimes;
            var pK_MuwaqqitPrayerTimesUc = RelationalModel.GetKey(this,
                "PrayerTimeEngine.Core.Domain.Calculators.Muwaqqit.Models.MuwaqqitPrayerTimes",
                new[] { "ID" });
            pK_MuwaqqitPrayerTimes.MappedKeys.Add(pK_MuwaqqitPrayerTimesUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_MuwaqqitPrayerTimesUc).Add(pK_MuwaqqitPrayerTimes);
            muwaqqitPrayerTimesTable.UniqueConstraints.Add("PK_MuwaqqitPrayerTimes", pK_MuwaqqitPrayerTimes);
            relationalModel.Tables.Add(("MuwaqqitPrayerTimes", null), muwaqqitPrayerTimesTable);
            var muwaqqitPrayerTimesTableMapping = new TableMapping(muwaqqitPrayerTimes, muwaqqitPrayerTimesTable, true);
            muwaqqitPrayerTimesTable.AddTypeMapping(muwaqqitPrayerTimesTableMapping, false);
            tableMappings2.Add(muwaqqitPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(iDColumn2, muwaqqitPrayerTimes.FindProperty("ID")!, muwaqqitPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(asrColumn0, muwaqqitPrayerTimes.FindProperty("Asr")!, muwaqqitPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(asrKarahaColumn, muwaqqitPrayerTimes.FindProperty("AsrKaraha")!, muwaqqitPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(asrKarahaDegreeColumn, muwaqqitPrayerTimes.FindProperty("AsrKarahaDegree")!, muwaqqitPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(asrMithlaynColumn, muwaqqitPrayerTimes.FindProperty("AsrMithlayn")!, muwaqqitPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(dateColumn0, muwaqqitPrayerTimes.FindProperty("Date")!, muwaqqitPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(dhuhrColumn0, muwaqqitPrayerTimes.FindProperty("Dhuhr")!, muwaqqitPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(duhaColumn, muwaqqitPrayerTimes.FindProperty("Duha")!, muwaqqitPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(fajrColumn0, muwaqqitPrayerTimes.FindProperty("Fajr")!, muwaqqitPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(fajrDegreeColumn, muwaqqitPrayerTimes.FindProperty("FajrDegree")!, muwaqqitPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(insertInstantColumn, muwaqqitPrayerTimes.FindProperty("InsertInstant")!, muwaqqitPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(ishaColumn0, muwaqqitPrayerTimes.FindProperty("Isha")!, muwaqqitPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(ishaDegreeColumn, muwaqqitPrayerTimes.FindProperty("IshaDegree")!, muwaqqitPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(ishtibaqColumn, muwaqqitPrayerTimes.FindProperty("Ishtibaq")!, muwaqqitPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(ishtibaqDegreeColumn, muwaqqitPrayerTimes.FindProperty("IshtibaqDegree")!, muwaqqitPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(latitudeColumn, muwaqqitPrayerTimes.FindProperty("Latitude")!, muwaqqitPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(longitudeColumn, muwaqqitPrayerTimes.FindProperty("Longitude")!, muwaqqitPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(maghribColumn0, muwaqqitPrayerTimes.FindProperty("Maghrib")!, muwaqqitPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(nextFajrColumn0, muwaqqitPrayerTimes.FindProperty("NextFajr")!, muwaqqitPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(shuruqColumn0, muwaqqitPrayerTimes.FindProperty("Shuruq")!, muwaqqitPrayerTimesTableMapping);

            var semerkandCity = FindEntityType("PrayerTimeEngine.Core.Domain.Calculators.Semerkand.Models.SemerkandCity")!;

            var defaultTableMappings3 = new List<TableMappingBase<ColumnMappingBase>>();
            semerkandCity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings3);
            var prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCityTableBase = new TableBase("PrayerTimeEngine.Core.Domain.Calculators.Semerkand.Models.SemerkandCity", null, relationalModel);
            var countryIDColumnBase0 = new ColumnBase<ColumnMappingBase>("CountryID", "INTEGER", prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCityTableBase);
            prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCityTableBase.Columns.Add("CountryID", countryIDColumnBase0);
            var iDColumnBase3 = new ColumnBase<ColumnMappingBase>("ID", "INTEGER", prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCityTableBase);
            prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCityTableBase.Columns.Add("ID", iDColumnBase3);
            var nameColumnBase1 = new ColumnBase<ColumnMappingBase>("Name", "TEXT", prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCityTableBase)
            {
                IsNullable = true
            };
            prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCityTableBase.Columns.Add("Name", nameColumnBase1);
            relationalModel.DefaultTables.Add("PrayerTimeEngine.Core.Domain.Calculators.Semerkand.Models.SemerkandCity", prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCityTableBase);
            var prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCityMappingBase = new TableMappingBase<ColumnMappingBase>(semerkandCity, prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCityTableBase, true);
            prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCityTableBase.AddTypeMapping(prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCityMappingBase, false);
            defaultTableMappings3.Add(prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)iDColumnBase3, semerkandCity.FindProperty("ID")!, prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)countryIDColumnBase0, semerkandCity.FindProperty("CountryID")!, prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase1, semerkandCity.FindProperty("Name")!, prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCityMappingBase);

            var tableMappings3 = new List<TableMapping>();
            semerkandCity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings3);
            var semerkandCitiesTable = new Table("SemerkandCities", null, relationalModel);
            var iDColumn3 = new Column("ID", "INTEGER", semerkandCitiesTable);
            semerkandCitiesTable.Columns.Add("ID", iDColumn3);
            var countryIDColumn0 = new Column("CountryID", "INTEGER", semerkandCitiesTable);
            semerkandCitiesTable.Columns.Add("CountryID", countryIDColumn0);
            var nameColumn1 = new Column("Name", "TEXT", semerkandCitiesTable)
            {
                IsNullable = true
            };
            semerkandCitiesTable.Columns.Add("Name", nameColumn1);
            var pK_SemerkandCities = new UniqueConstraint("PK_SemerkandCities", semerkandCitiesTable, new[] { iDColumn3 });
            semerkandCitiesTable.PrimaryKey = pK_SemerkandCities;
            var pK_SemerkandCitiesUc = RelationalModel.GetKey(this,
                "PrayerTimeEngine.Core.Domain.Calculators.Semerkand.Models.SemerkandCity",
                new[] { "ID" });
            pK_SemerkandCities.MappedKeys.Add(pK_SemerkandCitiesUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_SemerkandCitiesUc).Add(pK_SemerkandCities);
            semerkandCitiesTable.UniqueConstraints.Add("PK_SemerkandCities", pK_SemerkandCities);
            var iX_SemerkandCities_CountryID = new TableIndex(
            "IX_SemerkandCities_CountryID", semerkandCitiesTable, new[] { countryIDColumn0 }, false);
            var iX_SemerkandCities_CountryIDIx = RelationalModel.GetIndex(this,
                "PrayerTimeEngine.Core.Domain.Calculators.Semerkand.Models.SemerkandCity",
                new[] { "CountryID" });
            iX_SemerkandCities_CountryID.MappedIndexes.Add(iX_SemerkandCities_CountryIDIx);
            RelationalModel.GetOrCreateTableIndexes(iX_SemerkandCities_CountryIDIx).Add(iX_SemerkandCities_CountryID);
            semerkandCitiesTable.Indexes.Add("IX_SemerkandCities_CountryID", iX_SemerkandCities_CountryID);
            relationalModel.Tables.Add(("SemerkandCities", null), semerkandCitiesTable);
            var semerkandCitiesTableMapping = new TableMapping(semerkandCity, semerkandCitiesTable, true);
            semerkandCitiesTable.AddTypeMapping(semerkandCitiesTableMapping, false);
            tableMappings3.Add(semerkandCitiesTableMapping);
            RelationalModel.CreateColumnMapping(iDColumn3, semerkandCity.FindProperty("ID")!, semerkandCitiesTableMapping);
            RelationalModel.CreateColumnMapping(countryIDColumn0, semerkandCity.FindProperty("CountryID")!, semerkandCitiesTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn1, semerkandCity.FindProperty("Name")!, semerkandCitiesTableMapping);

            var semerkandCountry = FindEntityType("PrayerTimeEngine.Core.Domain.Calculators.Semerkand.Models.SemerkandCountry")!;

            var defaultTableMappings4 = new List<TableMappingBase<ColumnMappingBase>>();
            semerkandCountry.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings4);
            var prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCountryTableBase = new TableBase("PrayerTimeEngine.Core.Domain.Calculators.Semerkand.Models.SemerkandCountry", null, relationalModel);
            var iDColumnBase4 = new ColumnBase<ColumnMappingBase>("ID", "INTEGER", prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCountryTableBase);
            prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCountryTableBase.Columns.Add("ID", iDColumnBase4);
            var nameColumnBase2 = new ColumnBase<ColumnMappingBase>("Name", "TEXT", prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCountryTableBase)
            {
                IsNullable = true
            };
            prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCountryTableBase.Columns.Add("Name", nameColumnBase2);
            relationalModel.DefaultTables.Add("PrayerTimeEngine.Core.Domain.Calculators.Semerkand.Models.SemerkandCountry", prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCountryTableBase);
            var prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCountryMappingBase = new TableMappingBase<ColumnMappingBase>(semerkandCountry, prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCountryTableBase, true);
            prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCountryTableBase.AddTypeMapping(prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCountryMappingBase, false);
            defaultTableMappings4.Add(prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCountryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)iDColumnBase4, semerkandCountry.FindProperty("ID")!, prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCountryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase2, semerkandCountry.FindProperty("Name")!, prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandCountryMappingBase);

            var tableMappings4 = new List<TableMapping>();
            semerkandCountry.SetRuntimeAnnotation("Relational:TableMappings", tableMappings4);
            var semerkandCountriesTable = new Table("SemerkandCountries", null, relationalModel);
            var iDColumn4 = new Column("ID", "INTEGER", semerkandCountriesTable);
            semerkandCountriesTable.Columns.Add("ID", iDColumn4);
            var nameColumn2 = new Column("Name", "TEXT", semerkandCountriesTable)
            {
                IsNullable = true
            };
            semerkandCountriesTable.Columns.Add("Name", nameColumn2);
            var pK_SemerkandCountries = new UniqueConstraint("PK_SemerkandCountries", semerkandCountriesTable, new[] { iDColumn4 });
            semerkandCountriesTable.PrimaryKey = pK_SemerkandCountries;
            var pK_SemerkandCountriesUc = RelationalModel.GetKey(this,
                "PrayerTimeEngine.Core.Domain.Calculators.Semerkand.Models.SemerkandCountry",
                new[] { "ID" });
            pK_SemerkandCountries.MappedKeys.Add(pK_SemerkandCountriesUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_SemerkandCountriesUc).Add(pK_SemerkandCountries);
            semerkandCountriesTable.UniqueConstraints.Add("PK_SemerkandCountries", pK_SemerkandCountries);
            relationalModel.Tables.Add(("SemerkandCountries", null), semerkandCountriesTable);
            var semerkandCountriesTableMapping = new TableMapping(semerkandCountry, semerkandCountriesTable, true);
            semerkandCountriesTable.AddTypeMapping(semerkandCountriesTableMapping, false);
            tableMappings4.Add(semerkandCountriesTableMapping);
            RelationalModel.CreateColumnMapping(iDColumn4, semerkandCountry.FindProperty("ID")!, semerkandCountriesTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn2, semerkandCountry.FindProperty("Name")!, semerkandCountriesTableMapping);

            var semerkandPrayerTimes = FindEntityType("PrayerTimeEngine.Core.Domain.Calculators.Semerkand.Models.SemerkandPrayerTimes")!;

            var defaultTableMappings5 = new List<TableMappingBase<ColumnMappingBase>>();
            semerkandPrayerTimes.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings5);
            var prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase = new TableBase("PrayerTimeEngine.Core.Domain.Calculators.Semerkand.Models.SemerkandPrayerTimes", null, relationalModel);
            var asrColumnBase1 = new ColumnBase<ColumnMappingBase>("Asr", "TEXT", prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase.Columns.Add("Asr", asrColumnBase1);
            var cityIDColumnBase0 = new ColumnBase<ColumnMappingBase>("CityID", "INTEGER", prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase.Columns.Add("CityID", cityIDColumnBase0);
            var dateColumnBase1 = new ColumnBase<ColumnMappingBase>("Date", "TEXT", prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase.Columns.Add("Date", dateColumnBase1);
            var dayOfYearColumnBase = new ColumnBase<ColumnMappingBase>("DayOfYear", "INTEGER", prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase.Columns.Add("DayOfYear", dayOfYearColumnBase);
            var dhuhrColumnBase1 = new ColumnBase<ColumnMappingBase>("Dhuhr", "TEXT", prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase.Columns.Add("Dhuhr", dhuhrColumnBase1);
            var fajrColumnBase1 = new ColumnBase<ColumnMappingBase>("Fajr", "TEXT", prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase.Columns.Add("Fajr", fajrColumnBase1);
            var iDColumnBase5 = new ColumnBase<ColumnMappingBase>("ID", "INTEGER", prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase.Columns.Add("ID", iDColumnBase5);
            var ishaColumnBase1 = new ColumnBase<ColumnMappingBase>("Isha", "TEXT", prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase.Columns.Add("Isha", ishaColumnBase1);
            var maghribColumnBase1 = new ColumnBase<ColumnMappingBase>("Maghrib", "TEXT", prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase.Columns.Add("Maghrib", maghribColumnBase1);
            var nextFajrColumnBase1 = new ColumnBase<ColumnMappingBase>("NextFajr", "TEXT", prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase)
            {
                IsNullable = true
            };
            prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase.Columns.Add("NextFajr", nextFajrColumnBase1);
            var shuruqColumnBase1 = new ColumnBase<ColumnMappingBase>("Shuruq", "TEXT", prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase);
            prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase.Columns.Add("Shuruq", shuruqColumnBase1);
            relationalModel.DefaultTables.Add("PrayerTimeEngine.Core.Domain.Calculators.Semerkand.Models.SemerkandPrayerTimes", prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase);
            var prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesMappingBase = new TableMappingBase<ColumnMappingBase>(semerkandPrayerTimes, prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase, true);
            prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesTableBase.AddTypeMapping(prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesMappingBase, false);
            defaultTableMappings5.Add(prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)iDColumnBase5, semerkandPrayerTimes.FindProperty("ID")!, prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)asrColumnBase1, semerkandPrayerTimes.FindProperty("Asr")!, prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)cityIDColumnBase0, semerkandPrayerTimes.FindProperty("CityID")!, prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)dateColumnBase1, semerkandPrayerTimes.FindProperty("Date")!, prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)dayOfYearColumnBase, semerkandPrayerTimes.FindProperty("DayOfYear")!, prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)dhuhrColumnBase1, semerkandPrayerTimes.FindProperty("Dhuhr")!, prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)fajrColumnBase1, semerkandPrayerTimes.FindProperty("Fajr")!, prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)ishaColumnBase1, semerkandPrayerTimes.FindProperty("Isha")!, prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)maghribColumnBase1, semerkandPrayerTimes.FindProperty("Maghrib")!, prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nextFajrColumnBase1, semerkandPrayerTimes.FindProperty("NextFajr")!, prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)shuruqColumnBase1, semerkandPrayerTimes.FindProperty("Shuruq")!, prayerTimeEngineCoreDomainCalculatorsSemerkandModelsSemerkandPrayerTimesMappingBase);

            var tableMappings5 = new List<TableMapping>();
            semerkandPrayerTimes.SetRuntimeAnnotation("Relational:TableMappings", tableMappings5);
            var semerkandPrayerTimesTable = new Table("SemerkandPrayerTimes", null, relationalModel);
            var iDColumn5 = new Column("ID", "INTEGER", semerkandPrayerTimesTable);
            semerkandPrayerTimesTable.Columns.Add("ID", iDColumn5);
            var asrColumn1 = new Column("Asr", "TEXT", semerkandPrayerTimesTable);
            semerkandPrayerTimesTable.Columns.Add("Asr", asrColumn1);
            var cityIDColumn0 = new Column("CityID", "INTEGER", semerkandPrayerTimesTable);
            semerkandPrayerTimesTable.Columns.Add("CityID", cityIDColumn0);
            var dateColumn1 = new Column("Date", "TEXT", semerkandPrayerTimesTable);
            semerkandPrayerTimesTable.Columns.Add("Date", dateColumn1);
            var dayOfYearColumn = new Column("DayOfYear", "INTEGER", semerkandPrayerTimesTable);
            semerkandPrayerTimesTable.Columns.Add("DayOfYear", dayOfYearColumn);
            var dhuhrColumn1 = new Column("Dhuhr", "TEXT", semerkandPrayerTimesTable);
            semerkandPrayerTimesTable.Columns.Add("Dhuhr", dhuhrColumn1);
            var fajrColumn1 = new Column("Fajr", "TEXT", semerkandPrayerTimesTable);
            semerkandPrayerTimesTable.Columns.Add("Fajr", fajrColumn1);
            var ishaColumn1 = new Column("Isha", "TEXT", semerkandPrayerTimesTable);
            semerkandPrayerTimesTable.Columns.Add("Isha", ishaColumn1);
            var maghribColumn1 = new Column("Maghrib", "TEXT", semerkandPrayerTimesTable);
            semerkandPrayerTimesTable.Columns.Add("Maghrib", maghribColumn1);
            var nextFajrColumn1 = new Column("NextFajr", "TEXT", semerkandPrayerTimesTable)
            {
                IsNullable = true
            };
            semerkandPrayerTimesTable.Columns.Add("NextFajr", nextFajrColumn1);
            var shuruqColumn1 = new Column("Shuruq", "TEXT", semerkandPrayerTimesTable);
            semerkandPrayerTimesTable.Columns.Add("Shuruq", shuruqColumn1);
            var pK_SemerkandPrayerTimes = new UniqueConstraint("PK_SemerkandPrayerTimes", semerkandPrayerTimesTable, new[] { iDColumn5 });
            semerkandPrayerTimesTable.PrimaryKey = pK_SemerkandPrayerTimes;
            var pK_SemerkandPrayerTimesUc = RelationalModel.GetKey(this,
                "PrayerTimeEngine.Core.Domain.Calculators.Semerkand.Models.SemerkandPrayerTimes",
                new[] { "ID" });
            pK_SemerkandPrayerTimes.MappedKeys.Add(pK_SemerkandPrayerTimesUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_SemerkandPrayerTimesUc).Add(pK_SemerkandPrayerTimes);
            semerkandPrayerTimesTable.UniqueConstraints.Add("PK_SemerkandPrayerTimes", pK_SemerkandPrayerTimes);
            relationalModel.Tables.Add(("SemerkandPrayerTimes", null), semerkandPrayerTimesTable);
            var semerkandPrayerTimesTableMapping = new TableMapping(semerkandPrayerTimes, semerkandPrayerTimesTable, true);
            semerkandPrayerTimesTable.AddTypeMapping(semerkandPrayerTimesTableMapping, false);
            tableMappings5.Add(semerkandPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(iDColumn5, semerkandPrayerTimes.FindProperty("ID")!, semerkandPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(asrColumn1, semerkandPrayerTimes.FindProperty("Asr")!, semerkandPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(cityIDColumn0, semerkandPrayerTimes.FindProperty("CityID")!, semerkandPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(dateColumn1, semerkandPrayerTimes.FindProperty("Date")!, semerkandPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(dayOfYearColumn, semerkandPrayerTimes.FindProperty("DayOfYear")!, semerkandPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(dhuhrColumn1, semerkandPrayerTimes.FindProperty("Dhuhr")!, semerkandPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(fajrColumn1, semerkandPrayerTimes.FindProperty("Fajr")!, semerkandPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(ishaColumn1, semerkandPrayerTimes.FindProperty("Isha")!, semerkandPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(maghribColumn1, semerkandPrayerTimes.FindProperty("Maghrib")!, semerkandPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(nextFajrColumn1, semerkandPrayerTimes.FindProperty("NextFajr")!, semerkandPrayerTimesTableMapping);
            RelationalModel.CreateColumnMapping(shuruqColumn1, semerkandPrayerTimes.FindProperty("Shuruq")!, semerkandPrayerTimesTableMapping);

            var profile = FindEntityType("PrayerTimeEngine.Core.Domain.Configuration.Models.Profile")!;

            var defaultTableMappings6 = new List<TableMappingBase<ColumnMappingBase>>();
            profile.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings6);
            var prayerTimeEngineCoreDomainConfigurationModelsProfileTableBase = new TableBase("PrayerTimeEngine.Core.Domain.Configuration.Models.Profile", null, relationalModel);
            var iDColumnBase6 = new ColumnBase<ColumnMappingBase>("ID", "INTEGER", prayerTimeEngineCoreDomainConfigurationModelsProfileTableBase);
            prayerTimeEngineCoreDomainConfigurationModelsProfileTableBase.Columns.Add("ID", iDColumnBase6);
            var locationNameColumnBase = new ColumnBase<ColumnMappingBase>("LocationName", "TEXT", prayerTimeEngineCoreDomainConfigurationModelsProfileTableBase)
            {
                IsNullable = true
            };
            prayerTimeEngineCoreDomainConfigurationModelsProfileTableBase.Columns.Add("LocationName", locationNameColumnBase);
            var nameColumnBase3 = new ColumnBase<ColumnMappingBase>("Name", "TEXT", prayerTimeEngineCoreDomainConfigurationModelsProfileTableBase)
            {
                IsNullable = true
            };
            prayerTimeEngineCoreDomainConfigurationModelsProfileTableBase.Columns.Add("Name", nameColumnBase3);
            var sequenceNoColumnBase = new ColumnBase<ColumnMappingBase>("SequenceNo", "INTEGER", prayerTimeEngineCoreDomainConfigurationModelsProfileTableBase);
            prayerTimeEngineCoreDomainConfigurationModelsProfileTableBase.Columns.Add("SequenceNo", sequenceNoColumnBase);
            relationalModel.DefaultTables.Add("PrayerTimeEngine.Core.Domain.Configuration.Models.Profile", prayerTimeEngineCoreDomainConfigurationModelsProfileTableBase);
            var prayerTimeEngineCoreDomainConfigurationModelsProfileMappingBase = new TableMappingBase<ColumnMappingBase>(profile, prayerTimeEngineCoreDomainConfigurationModelsProfileTableBase, true);
            prayerTimeEngineCoreDomainConfigurationModelsProfileTableBase.AddTypeMapping(prayerTimeEngineCoreDomainConfigurationModelsProfileMappingBase, false);
            defaultTableMappings6.Add(prayerTimeEngineCoreDomainConfigurationModelsProfileMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)iDColumnBase6, profile.FindProperty("ID")!, prayerTimeEngineCoreDomainConfigurationModelsProfileMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)locationNameColumnBase, profile.FindProperty("LocationName")!, prayerTimeEngineCoreDomainConfigurationModelsProfileMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase3, profile.FindProperty("Name")!, prayerTimeEngineCoreDomainConfigurationModelsProfileMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)sequenceNoColumnBase, profile.FindProperty("SequenceNo")!, prayerTimeEngineCoreDomainConfigurationModelsProfileMappingBase);

            var tableMappings6 = new List<TableMapping>();
            profile.SetRuntimeAnnotation("Relational:TableMappings", tableMappings6);
            var profilesTable = new Table("Profiles", null, relationalModel);
            var iDColumn6 = new Column("ID", "INTEGER", profilesTable);
            profilesTable.Columns.Add("ID", iDColumn6);
            var locationNameColumn = new Column("LocationName", "TEXT", profilesTable)
            {
                IsNullable = true
            };
            profilesTable.Columns.Add("LocationName", locationNameColumn);
            var nameColumn3 = new Column("Name", "TEXT", profilesTable)
            {
                IsNullable = true
            };
            profilesTable.Columns.Add("Name", nameColumn3);
            var sequenceNoColumn = new Column("SequenceNo", "INTEGER", profilesTable);
            profilesTable.Columns.Add("SequenceNo", sequenceNoColumn);
            var pK_Profiles = new UniqueConstraint("PK_Profiles", profilesTable, new[] { iDColumn6 });
            profilesTable.PrimaryKey = pK_Profiles;
            var pK_ProfilesUc = RelationalModel.GetKey(this,
                "PrayerTimeEngine.Core.Domain.Configuration.Models.Profile",
                new[] { "ID" });
            pK_Profiles.MappedKeys.Add(pK_ProfilesUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_ProfilesUc).Add(pK_Profiles);
            profilesTable.UniqueConstraints.Add("PK_Profiles", pK_Profiles);
            relationalModel.Tables.Add(("Profiles", null), profilesTable);
            var profilesTableMapping = new TableMapping(profile, profilesTable, true);
            profilesTable.AddTypeMapping(profilesTableMapping, false);
            tableMappings6.Add(profilesTableMapping);
            RelationalModel.CreateColumnMapping(iDColumn6, profile.FindProperty("ID")!, profilesTableMapping);
            RelationalModel.CreateColumnMapping(locationNameColumn, profile.FindProperty("LocationName")!, profilesTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn3, profile.FindProperty("Name")!, profilesTableMapping);
            RelationalModel.CreateColumnMapping(sequenceNoColumn, profile.FindProperty("SequenceNo")!, profilesTableMapping);

            var profileLocationConfig = FindEntityType("PrayerTimeEngine.Core.Domain.Configuration.Models.ProfileLocationConfig")!;

            var defaultTableMappings7 = new List<TableMappingBase<ColumnMappingBase>>();
            profileLocationConfig.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings7);
            var prayerTimeEngineCoreDomainConfigurationModelsProfileLocationConfigTableBase = new TableBase("PrayerTimeEngine.Core.Domain.Configuration.Models.ProfileLocationConfig", null, relationalModel);
            var calculationSourceColumnBase = new ColumnBase<ColumnMappingBase>("CalculationSource", "INTEGER", prayerTimeEngineCoreDomainConfigurationModelsProfileLocationConfigTableBase);
            prayerTimeEngineCoreDomainConfigurationModelsProfileLocationConfigTableBase.Columns.Add("CalculationSource", calculationSourceColumnBase);
            var iDColumnBase7 = new ColumnBase<ColumnMappingBase>("ID", "INTEGER", prayerTimeEngineCoreDomainConfigurationModelsProfileLocationConfigTableBase);
            prayerTimeEngineCoreDomainConfigurationModelsProfileLocationConfigTableBase.Columns.Add("ID", iDColumnBase7);
            var locationDataColumnBase = new ColumnBase<ColumnMappingBase>("LocationData", "TEXT", prayerTimeEngineCoreDomainConfigurationModelsProfileLocationConfigTableBase)
            {
                IsNullable = true
            };
            prayerTimeEngineCoreDomainConfigurationModelsProfileLocationConfigTableBase.Columns.Add("LocationData", locationDataColumnBase);
            var profileIDColumnBase = new ColumnBase<ColumnMappingBase>("ProfileID", "INTEGER", prayerTimeEngineCoreDomainConfigurationModelsProfileLocationConfigTableBase);
            prayerTimeEngineCoreDomainConfigurationModelsProfileLocationConfigTableBase.Columns.Add("ProfileID", profileIDColumnBase);
            relationalModel.DefaultTables.Add("PrayerTimeEngine.Core.Domain.Configuration.Models.ProfileLocationConfig", prayerTimeEngineCoreDomainConfigurationModelsProfileLocationConfigTableBase);
            var prayerTimeEngineCoreDomainConfigurationModelsProfileLocationConfigMappingBase = new TableMappingBase<ColumnMappingBase>(profileLocationConfig, prayerTimeEngineCoreDomainConfigurationModelsProfileLocationConfigTableBase, true);
            prayerTimeEngineCoreDomainConfigurationModelsProfileLocationConfigTableBase.AddTypeMapping(prayerTimeEngineCoreDomainConfigurationModelsProfileLocationConfigMappingBase, false);
            defaultTableMappings7.Add(prayerTimeEngineCoreDomainConfigurationModelsProfileLocationConfigMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)iDColumnBase7, profileLocationConfig.FindProperty("ID")!, prayerTimeEngineCoreDomainConfigurationModelsProfileLocationConfigMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)calculationSourceColumnBase, profileLocationConfig.FindProperty("CalculationSource")!, prayerTimeEngineCoreDomainConfigurationModelsProfileLocationConfigMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)locationDataColumnBase, profileLocationConfig.FindProperty("LocationData")!, prayerTimeEngineCoreDomainConfigurationModelsProfileLocationConfigMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)profileIDColumnBase, profileLocationConfig.FindProperty("ProfileID")!, prayerTimeEngineCoreDomainConfigurationModelsProfileLocationConfigMappingBase);

            var tableMappings7 = new List<TableMapping>();
            profileLocationConfig.SetRuntimeAnnotation("Relational:TableMappings", tableMappings7);
            var profileLocationsTable = new Table("ProfileLocations", null, relationalModel);
            var iDColumn7 = new Column("ID", "INTEGER", profileLocationsTable);
            profileLocationsTable.Columns.Add("ID", iDColumn7);
            var calculationSourceColumn = new Column("CalculationSource", "INTEGER", profileLocationsTable);
            profileLocationsTable.Columns.Add("CalculationSource", calculationSourceColumn);
            var locationDataColumn = new Column("LocationData", "TEXT", profileLocationsTable)
            {
                IsNullable = true
            };
            profileLocationsTable.Columns.Add("LocationData", locationDataColumn);
            var profileIDColumn = new Column("ProfileID", "INTEGER", profileLocationsTable);
            profileLocationsTable.Columns.Add("ProfileID", profileIDColumn);
            var pK_ProfileLocations = new UniqueConstraint("PK_ProfileLocations", profileLocationsTable, new[] { iDColumn7 });
            profileLocationsTable.PrimaryKey = pK_ProfileLocations;
            var pK_ProfileLocationsUc = RelationalModel.GetKey(this,
                "PrayerTimeEngine.Core.Domain.Configuration.Models.ProfileLocationConfig",
                new[] { "ID" });
            pK_ProfileLocations.MappedKeys.Add(pK_ProfileLocationsUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_ProfileLocationsUc).Add(pK_ProfileLocations);
            profileLocationsTable.UniqueConstraints.Add("PK_ProfileLocations", pK_ProfileLocations);
            var iX_ProfileLocations_ProfileID = new TableIndex(
            "IX_ProfileLocations_ProfileID", profileLocationsTable, new[] { profileIDColumn }, false);
            var iX_ProfileLocations_ProfileIDIx = RelationalModel.GetIndex(this,
                "PrayerTimeEngine.Core.Domain.Configuration.Models.ProfileLocationConfig",
                new[] { "ProfileID" });
            iX_ProfileLocations_ProfileID.MappedIndexes.Add(iX_ProfileLocations_ProfileIDIx);
            RelationalModel.GetOrCreateTableIndexes(iX_ProfileLocations_ProfileIDIx).Add(iX_ProfileLocations_ProfileID);
            profileLocationsTable.Indexes.Add("IX_ProfileLocations_ProfileID", iX_ProfileLocations_ProfileID);
            relationalModel.Tables.Add(("ProfileLocations", null), profileLocationsTable);
            var profileLocationsTableMapping = new TableMapping(profileLocationConfig, profileLocationsTable, true);
            profileLocationsTable.AddTypeMapping(profileLocationsTableMapping, false);
            tableMappings7.Add(profileLocationsTableMapping);
            RelationalModel.CreateColumnMapping(iDColumn7, profileLocationConfig.FindProperty("ID")!, profileLocationsTableMapping);
            RelationalModel.CreateColumnMapping(calculationSourceColumn, profileLocationConfig.FindProperty("CalculationSource")!, profileLocationsTableMapping);
            RelationalModel.CreateColumnMapping(locationDataColumn, profileLocationConfig.FindProperty("LocationData")!, profileLocationsTableMapping);
            RelationalModel.CreateColumnMapping(profileIDColumn, profileLocationConfig.FindProperty("ProfileID")!, profileLocationsTableMapping);

            var profileTimeConfig = FindEntityType("PrayerTimeEngine.Core.Domain.Configuration.Models.ProfileTimeConfig")!;

            var defaultTableMappings8 = new List<TableMappingBase<ColumnMappingBase>>();
            profileTimeConfig.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings8);
            var prayerTimeEngineCoreDomainConfigurationModelsProfileTimeConfigTableBase = new TableBase("PrayerTimeEngine.Core.Domain.Configuration.Models.ProfileTimeConfig", null, relationalModel);
            var calculationConfigurationColumnBase = new ColumnBase<ColumnMappingBase>("CalculationConfiguration", "TEXT", prayerTimeEngineCoreDomainConfigurationModelsProfileTimeConfigTableBase)
            {
                IsNullable = true
            };
            prayerTimeEngineCoreDomainConfigurationModelsProfileTimeConfigTableBase.Columns.Add("CalculationConfiguration", calculationConfigurationColumnBase);
            var iDColumnBase8 = new ColumnBase<ColumnMappingBase>("ID", "INTEGER", prayerTimeEngineCoreDomainConfigurationModelsProfileTimeConfigTableBase);
            prayerTimeEngineCoreDomainConfigurationModelsProfileTimeConfigTableBase.Columns.Add("ID", iDColumnBase8);
            var profileIDColumnBase0 = new ColumnBase<ColumnMappingBase>("ProfileID", "INTEGER", prayerTimeEngineCoreDomainConfigurationModelsProfileTimeConfigTableBase);
            prayerTimeEngineCoreDomainConfigurationModelsProfileTimeConfigTableBase.Columns.Add("ProfileID", profileIDColumnBase0);
            var timeTypeColumnBase = new ColumnBase<ColumnMappingBase>("TimeType", "INTEGER", prayerTimeEngineCoreDomainConfigurationModelsProfileTimeConfigTableBase);
            prayerTimeEngineCoreDomainConfigurationModelsProfileTimeConfigTableBase.Columns.Add("TimeType", timeTypeColumnBase);
            relationalModel.DefaultTables.Add("PrayerTimeEngine.Core.Domain.Configuration.Models.ProfileTimeConfig", prayerTimeEngineCoreDomainConfigurationModelsProfileTimeConfigTableBase);
            var prayerTimeEngineCoreDomainConfigurationModelsProfileTimeConfigMappingBase = new TableMappingBase<ColumnMappingBase>(profileTimeConfig, prayerTimeEngineCoreDomainConfigurationModelsProfileTimeConfigTableBase, true);
            prayerTimeEngineCoreDomainConfigurationModelsProfileTimeConfigTableBase.AddTypeMapping(prayerTimeEngineCoreDomainConfigurationModelsProfileTimeConfigMappingBase, false);
            defaultTableMappings8.Add(prayerTimeEngineCoreDomainConfigurationModelsProfileTimeConfigMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)iDColumnBase8, profileTimeConfig.FindProperty("ID")!, prayerTimeEngineCoreDomainConfigurationModelsProfileTimeConfigMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)calculationConfigurationColumnBase, profileTimeConfig.FindProperty("CalculationConfiguration")!, prayerTimeEngineCoreDomainConfigurationModelsProfileTimeConfigMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)profileIDColumnBase0, profileTimeConfig.FindProperty("ProfileID")!, prayerTimeEngineCoreDomainConfigurationModelsProfileTimeConfigMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)timeTypeColumnBase, profileTimeConfig.FindProperty("TimeType")!, prayerTimeEngineCoreDomainConfigurationModelsProfileTimeConfigMappingBase);

            var tableMappings8 = new List<TableMapping>();
            profileTimeConfig.SetRuntimeAnnotation("Relational:TableMappings", tableMappings8);
            var profileConfigsTable = new Table("ProfileConfigs", null, relationalModel);
            var iDColumn8 = new Column("ID", "INTEGER", profileConfigsTable);
            profileConfigsTable.Columns.Add("ID", iDColumn8);
            var calculationConfigurationColumn = new Column("CalculationConfiguration", "TEXT", profileConfigsTable)
            {
                IsNullable = true
            };
            profileConfigsTable.Columns.Add("CalculationConfiguration", calculationConfigurationColumn);
            var profileIDColumn0 = new Column("ProfileID", "INTEGER", profileConfigsTable);
            profileConfigsTable.Columns.Add("ProfileID", profileIDColumn0);
            var timeTypeColumn = new Column("TimeType", "INTEGER", profileConfigsTable);
            profileConfigsTable.Columns.Add("TimeType", timeTypeColumn);
            var pK_ProfileConfigs = new UniqueConstraint("PK_ProfileConfigs", profileConfigsTable, new[] { iDColumn8 });
            profileConfigsTable.PrimaryKey = pK_ProfileConfigs;
            var pK_ProfileConfigsUc = RelationalModel.GetKey(this,
                "PrayerTimeEngine.Core.Domain.Configuration.Models.ProfileTimeConfig",
                new[] { "ID" });
            pK_ProfileConfigs.MappedKeys.Add(pK_ProfileConfigsUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_ProfileConfigsUc).Add(pK_ProfileConfigs);
            profileConfigsTable.UniqueConstraints.Add("PK_ProfileConfigs", pK_ProfileConfigs);
            var iX_ProfileConfigs_ProfileID = new TableIndex(
            "IX_ProfileConfigs_ProfileID", profileConfigsTable, new[] { profileIDColumn0 }, false);
            var iX_ProfileConfigs_ProfileIDIx = RelationalModel.GetIndex(this,
                "PrayerTimeEngine.Core.Domain.Configuration.Models.ProfileTimeConfig",
                new[] { "ProfileID" });
            iX_ProfileConfigs_ProfileID.MappedIndexes.Add(iX_ProfileConfigs_ProfileIDIx);
            RelationalModel.GetOrCreateTableIndexes(iX_ProfileConfigs_ProfileIDIx).Add(iX_ProfileConfigs_ProfileID);
            profileConfigsTable.Indexes.Add("IX_ProfileConfigs_ProfileID", iX_ProfileConfigs_ProfileID);
            relationalModel.Tables.Add(("ProfileConfigs", null), profileConfigsTable);
            var profileConfigsTableMapping = new TableMapping(profileTimeConfig, profileConfigsTable, true);
            profileConfigsTable.AddTypeMapping(profileConfigsTableMapping, false);
            tableMappings8.Add(profileConfigsTableMapping);
            RelationalModel.CreateColumnMapping(iDColumn8, profileTimeConfig.FindProperty("ID")!, profileConfigsTableMapping);
            RelationalModel.CreateColumnMapping(calculationConfigurationColumn, profileTimeConfig.FindProperty("CalculationConfiguration")!, profileConfigsTableMapping);
            RelationalModel.CreateColumnMapping(profileIDColumn0, profileTimeConfig.FindProperty("ProfileID")!, profileConfigsTableMapping);
            RelationalModel.CreateColumnMapping(timeTypeColumn, profileTimeConfig.FindProperty("TimeType")!, profileConfigsTableMapping);
            var fK_FaziletCities_FaziletCountries_CountryID = new ForeignKeyConstraint(
                "FK_FaziletCities_FaziletCountries_CountryID", faziletCitiesTable, faziletCountriesTable,
                new[] { countryIDColumn },
                faziletCountriesTable.FindUniqueConstraint("PK_FaziletCountries")!, ReferentialAction.Cascade);
            var fK_FaziletCities_FaziletCountries_CountryIDFk = RelationalModel.GetForeignKey(this,
                "PrayerTimeEngine.Core.Domain.Calculators.Fazilet.Models.FaziletCity",
                new[] { "CountryID" },
                "PrayerTimeEngine.Core.Domain.Calculators.Fazilet.Models.FaziletCountry",
                new[] { "ID" });
            fK_FaziletCities_FaziletCountries_CountryID.MappedForeignKeys.Add(fK_FaziletCities_FaziletCountries_CountryIDFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_FaziletCities_FaziletCountries_CountryIDFk).Add(fK_FaziletCities_FaziletCountries_CountryID);
            faziletCitiesTable.ForeignKeyConstraints.Add(fK_FaziletCities_FaziletCountries_CountryID);
            faziletCountriesTable.ReferencingForeignKeyConstraints.Add(fK_FaziletCities_FaziletCountries_CountryID);
            var fK_ProfileConfigs_Profiles_ProfileID = new ForeignKeyConstraint(
                "FK_ProfileConfigs_Profiles_ProfileID", profileConfigsTable, profilesTable,
                new[] { profileIDColumn0 },
                profilesTable.FindUniqueConstraint("PK_Profiles")!, ReferentialAction.Cascade);
            var fK_ProfileConfigs_Profiles_ProfileIDFk = RelationalModel.GetForeignKey(this,
                "PrayerTimeEngine.Core.Domain.Configuration.Models.ProfileTimeConfig",
                new[] { "ProfileID" },
                "PrayerTimeEngine.Core.Domain.Configuration.Models.Profile",
                new[] { "ID" });
            fK_ProfileConfigs_Profiles_ProfileID.MappedForeignKeys.Add(fK_ProfileConfigs_Profiles_ProfileIDFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_ProfileConfigs_Profiles_ProfileIDFk).Add(fK_ProfileConfigs_Profiles_ProfileID);
            profileConfigsTable.ForeignKeyConstraints.Add(fK_ProfileConfigs_Profiles_ProfileID);
            profilesTable.ReferencingForeignKeyConstraints.Add(fK_ProfileConfigs_Profiles_ProfileID);
            var fK_ProfileLocations_Profiles_ProfileID = new ForeignKeyConstraint(
                "FK_ProfileLocations_Profiles_ProfileID", profileLocationsTable, profilesTable,
                new[] { profileIDColumn },
                profilesTable.FindUniqueConstraint("PK_Profiles")!, ReferentialAction.Cascade);
            var fK_ProfileLocations_Profiles_ProfileIDFk = RelationalModel.GetForeignKey(this,
                "PrayerTimeEngine.Core.Domain.Configuration.Models.ProfileLocationConfig",
                new[] { "ProfileID" },
                "PrayerTimeEngine.Core.Domain.Configuration.Models.Profile",
                new[] { "ID" });
            fK_ProfileLocations_Profiles_ProfileID.MappedForeignKeys.Add(fK_ProfileLocations_Profiles_ProfileIDFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_ProfileLocations_Profiles_ProfileIDFk).Add(fK_ProfileLocations_Profiles_ProfileID);
            profileLocationsTable.ForeignKeyConstraints.Add(fK_ProfileLocations_Profiles_ProfileID);
            profilesTable.ReferencingForeignKeyConstraints.Add(fK_ProfileLocations_Profiles_ProfileID);
            var fK_SemerkandCities_SemerkandCountries_CountryID = new ForeignKeyConstraint(
                "FK_SemerkandCities_SemerkandCountries_CountryID", semerkandCitiesTable, semerkandCountriesTable,
                new[] { countryIDColumn0 },
                semerkandCountriesTable.FindUniqueConstraint("PK_SemerkandCountries")!, ReferentialAction.Cascade);
            var fK_SemerkandCities_SemerkandCountries_CountryIDFk = RelationalModel.GetForeignKey(this,
                "PrayerTimeEngine.Core.Domain.Calculators.Semerkand.Models.SemerkandCity",
                new[] { "CountryID" },
                "PrayerTimeEngine.Core.Domain.Calculators.Semerkand.Models.SemerkandCountry",
                new[] { "ID" });
            fK_SemerkandCities_SemerkandCountries_CountryID.MappedForeignKeys.Add(fK_SemerkandCities_SemerkandCountries_CountryIDFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_SemerkandCities_SemerkandCountries_CountryIDFk).Add(fK_SemerkandCities_SemerkandCountries_CountryID);
            semerkandCitiesTable.ForeignKeyConstraints.Add(fK_SemerkandCities_SemerkandCountries_CountryID);
            semerkandCountriesTable.ReferencingForeignKeyConstraints.Add(fK_SemerkandCities_SemerkandCountries_CountryID);
            return relationalModel.MakeReadOnly();
        }
    }
}
