// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace PrayerTimeEngine.Core.Data.EntityFramework.Generated_CompiledModels
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("3e644a1f-73da-43e7-b22a-c508afcdacd6"), entityTypeCount: 16)
        {
        }

        partial void Initialize()
        {
            var faziletCity = FaziletCityEntityType.Create(this);
            var faziletCountry = FaziletCountryEntityType.Create(this);
            var faziletDailyPrayerTimes = FaziletDailyPrayerTimesEntityType.Create(this);
            var muwaqqitDailyPrayerTimes = MuwaqqitDailyPrayerTimesEntityType.Create(this);
            var semerkandCity = SemerkandCityEntityType.Create(this);
            var semerkandCountry = SemerkandCountryEntityType.Create(this);
            var semerkandDailyPrayerTimes = SemerkandDailyPrayerTimesEntityType.Create(this);
            var mawaqitMosqueDailyPrayerTimes = MawaqitMosqueDailyPrayerTimesEntityType.Create(this);
            var myMosqMosqueDailyPrayerTimes = MyMosqMosqueDailyPrayerTimesEntityType.Create(this);
            var profilePlaceInfo = ProfilePlaceInfoEntityType.Create(this);
            var timezoneInfo = TimezoneInfoEntityType.Create(this);
            var profile = ProfileEntityType.Create(this);
            var profileLocationConfig = ProfileLocationConfigEntityType.Create(this);
            var profileTimeConfig = ProfileTimeConfigEntityType.Create(this);
            var dynamicProfile = DynamicProfileEntityType.Create(this, profile);
            var mosqueProfile = MosqueProfileEntityType.Create(this, profile);

            FaziletCityEntityType.CreateForeignKey1(faziletCity, faziletCountry);
            SemerkandCityEntityType.CreateForeignKey1(semerkandCity, semerkandCountry);
            ProfilePlaceInfoEntityType.CreateForeignKey1(profilePlaceInfo, dynamicProfile);
            ProfilePlaceInfoEntityType.CreateForeignKey2(profilePlaceInfo, timezoneInfo);
            ProfileLocationConfigEntityType.CreateForeignKey1(profileLocationConfig, dynamicProfile);
            ProfileTimeConfigEntityType.CreateForeignKey1(profileTimeConfig, dynamicProfile);

            FaziletCityEntityType.CreateAnnotations(faziletCity);
            FaziletCountryEntityType.CreateAnnotations(faziletCountry);
            FaziletDailyPrayerTimesEntityType.CreateAnnotations(faziletDailyPrayerTimes);
            MuwaqqitDailyPrayerTimesEntityType.CreateAnnotations(muwaqqitDailyPrayerTimes);
            SemerkandCityEntityType.CreateAnnotations(semerkandCity);
            SemerkandCountryEntityType.CreateAnnotations(semerkandCountry);
            SemerkandDailyPrayerTimesEntityType.CreateAnnotations(semerkandDailyPrayerTimes);
            MawaqitMosqueDailyPrayerTimesEntityType.CreateAnnotations(mawaqitMosqueDailyPrayerTimes);
            MyMosqMosqueDailyPrayerTimesEntityType.CreateAnnotations(myMosqMosqueDailyPrayerTimes);
            ProfilePlaceInfoEntityType.CreateAnnotations(profilePlaceInfo);
            TimezoneInfoEntityType.CreateAnnotations(timezoneInfo);
            ProfileEntityType.CreateAnnotations(profile);
            ProfileLocationConfigEntityType.CreateAnnotations(profileLocationConfig);
            ProfileTimeConfigEntityType.CreateAnnotations(profileTimeConfig);
            DynamicProfileEntityType.CreateAnnotations(dynamicProfile);
            MosqueProfileEntityType.CreateAnnotations(mosqueProfile);

            AddAnnotation("ProductVersion", "9.0.4");
        }
    }
}
