// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using PrayerTimeEngine.Core.Common.Extension;
using PrayerTimeEngine.Core.Domain.DynamicPrayerTimes.Providers.Muwaqqit.Models.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace PrayerTimeEngine.Core.Data.EntityFramework.Generated_CompiledModels
{
    internal partial class MuwaqqitDailyPrayerTimesEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "PrayerTimeEngine.Core.Domain.DynamicPrayerTimes.Providers.Muwaqqit.Models.Entities.MuwaqqitDailyPrayerTimes",
                typeof(MuwaqqitDailyPrayerTimes),
                baseEntityType);

            var iD = runtimeEntityType.AddProperty(
                "ID",
                typeof(int),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("ID", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<ID>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            iD.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v),
                keyComparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var asr = runtimeEntityType.AddProperty(
                "Asr",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Asr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Asr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            asr.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                keyComparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                converter: new ValueConverter<ZonedDateTime, string>(
                    (ZonedDateTime x) => x.GetStringForDBColumn(),
                    (string x) => x.GetZonedDateTimeFromDBColumnString()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<ZonedDateTime, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<ZonedDateTime, string>(
                        (ZonedDateTime x) => x.GetStringForDBColumn(),
                        (string x) => x.GetZonedDateTimeFromDBColumnString())));
            asr.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var asrKaraha = runtimeEntityType.AddProperty(
                "AsrKaraha",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("AsrKaraha", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<AsrKaraha>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            asrKaraha.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                keyComparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                converter: new ValueConverter<ZonedDateTime, string>(
                    (ZonedDateTime x) => x.GetStringForDBColumn(),
                    (string x) => x.GetZonedDateTimeFromDBColumnString()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<ZonedDateTime, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<ZonedDateTime, string>(
                        (ZonedDateTime x) => x.GetStringForDBColumn(),
                        (string x) => x.GetZonedDateTimeFromDBColumnString())));
            asrKaraha.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var asrKarahaDegree = runtimeEntityType.AddProperty(
                "AsrKarahaDegree",
                typeof(double),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("AsrKarahaDegree", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<AsrKarahaDegree>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);
            asrKarahaDegree.TypeMapping = DoubleTypeMapping.Default.Clone(
                comparer: new ValueComparer<double>(
                    (double v1, double v2) => v1.Equals(v2),
                    (double v) => v.GetHashCode(),
                    (double v) => v),
                keyComparer: new ValueComparer<double>(
                    (double v1, double v2) => v1.Equals(v2),
                    (double v) => v.GetHashCode(),
                    (double v) => v),
                providerValueComparer: new ValueComparer<double>(
                    (double v1, double v2) => v1.Equals(v2),
                    (double v) => v.GetHashCode(),
                    (double v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "REAL"));

            var asrMithlayn = runtimeEntityType.AddProperty(
                "AsrMithlayn",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("AsrMithlayn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<AsrMithlayn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            asrMithlayn.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                keyComparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                converter: new ValueConverter<ZonedDateTime, string>(
                    (ZonedDateTime x) => x.GetStringForDBColumn(),
                    (string x) => x.GetZonedDateTimeFromDBColumnString()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<ZonedDateTime, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<ZonedDateTime, string>(
                        (ZonedDateTime x) => x.GetStringForDBColumn(),
                        (string x) => x.GetZonedDateTimeFromDBColumnString())));
            asrMithlayn.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var date = runtimeEntityType.AddProperty(
                "Date",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Date", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Date>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            date.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                keyComparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                converter: new ValueConverter<ZonedDateTime, string>(
                    (ZonedDateTime x) => x.GetStringForDBColumn(),
                    (string x) => x.GetZonedDateTimeFromDBColumnString()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<ZonedDateTime, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<ZonedDateTime, string>(
                        (ZonedDateTime x) => x.GetStringForDBColumn(),
                        (string x) => x.GetZonedDateTimeFromDBColumnString())));
            date.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var dhuhr = runtimeEntityType.AddProperty(
                "Dhuhr",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Dhuhr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Dhuhr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            dhuhr.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                keyComparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                converter: new ValueConverter<ZonedDateTime, string>(
                    (ZonedDateTime x) => x.GetStringForDBColumn(),
                    (string x) => x.GetZonedDateTimeFromDBColumnString()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<ZonedDateTime, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<ZonedDateTime, string>(
                        (ZonedDateTime x) => x.GetStringForDBColumn(),
                        (string x) => x.GetZonedDateTimeFromDBColumnString())));
            dhuhr.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var duha = runtimeEntityType.AddProperty(
                "Duha",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Duha", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Duha>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            duha.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                keyComparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                converter: new ValueConverter<ZonedDateTime, string>(
                    (ZonedDateTime x) => x.GetStringForDBColumn(),
                    (string x) => x.GetZonedDateTimeFromDBColumnString()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<ZonedDateTime, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<ZonedDateTime, string>(
                        (ZonedDateTime x) => x.GetStringForDBColumn(),
                        (string x) => x.GetZonedDateTimeFromDBColumnString())));
            duha.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var fajr = runtimeEntityType.AddProperty(
                "Fajr",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Fajr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Fajr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            fajr.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                keyComparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                converter: new ValueConverter<ZonedDateTime, string>(
                    (ZonedDateTime x) => x.GetStringForDBColumn(),
                    (string x) => x.GetZonedDateTimeFromDBColumnString()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<ZonedDateTime, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<ZonedDateTime, string>(
                        (ZonedDateTime x) => x.GetStringForDBColumn(),
                        (string x) => x.GetZonedDateTimeFromDBColumnString())));
            fajr.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var fajrDegree = runtimeEntityType.AddProperty(
                "FajrDegree",
                typeof(double),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("FajrDegree", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<FajrDegree>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);
            fajrDegree.TypeMapping = DoubleTypeMapping.Default.Clone(
                comparer: new ValueComparer<double>(
                    (double v1, double v2) => v1.Equals(v2),
                    (double v) => v.GetHashCode(),
                    (double v) => v),
                keyComparer: new ValueComparer<double>(
                    (double v1, double v2) => v1.Equals(v2),
                    (double v) => v.GetHashCode(),
                    (double v) => v),
                providerValueComparer: new ValueComparer<double>(
                    (double v1, double v2) => v1.Equals(v2),
                    (double v) => v.GetHashCode(),
                    (double v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "REAL"));

            var insertInstant = runtimeEntityType.AddProperty(
                "InsertInstant",
                typeof(Instant?),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("InsertInstant", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<InsertInstant>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            insertInstant.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<Instant?>(
                    (Nullable<Instant> v1, Nullable<Instant> v2) => object.Equals((object)v1, (object)v2),
                    (Nullable<Instant> v) => v.GetHashCode(),
                    (Nullable<Instant> v) => v),
                keyComparer: new ValueComparer<Instant?>(
                    (Nullable<Instant> v1, Nullable<Instant> v2) => object.Equals((object)v1, (object)v2),
                    (Nullable<Instant> v) => v.GetHashCode(),
                    (Nullable<Instant> v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                converter: new ValueConverter<Instant?, string>(
                    (Nullable<Instant> x) => x != null ? x.Value.GetStringForDBColumn() : null,
                    (string x) => x != null ? (Nullable<Instant>)x.GetInstantFromDBColumnString() : null),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<Instant?, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<Instant?, string>(
                        (Nullable<Instant> x) => x != null ? x.Value.GetStringForDBColumn() : null,
                        (string x) => x != null ? (Nullable<Instant>)x.GetInstantFromDBColumnString() : null)));

            var isha = runtimeEntityType.AddProperty(
                "Isha",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Isha", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Isha>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            isha.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                keyComparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                converter: new ValueConverter<ZonedDateTime, string>(
                    (ZonedDateTime x) => x.GetStringForDBColumn(),
                    (string x) => x.GetZonedDateTimeFromDBColumnString()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<ZonedDateTime, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<ZonedDateTime, string>(
                        (ZonedDateTime x) => x.GetStringForDBColumn(),
                        (string x) => x.GetZonedDateTimeFromDBColumnString())));
            isha.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var ishaDegree = runtimeEntityType.AddProperty(
                "IshaDegree",
                typeof(double),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("IshaDegree", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<IshaDegree>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);
            ishaDegree.TypeMapping = DoubleTypeMapping.Default.Clone(
                comparer: new ValueComparer<double>(
                    (double v1, double v2) => v1.Equals(v2),
                    (double v) => v.GetHashCode(),
                    (double v) => v),
                keyComparer: new ValueComparer<double>(
                    (double v1, double v2) => v1.Equals(v2),
                    (double v) => v.GetHashCode(),
                    (double v) => v),
                providerValueComparer: new ValueComparer<double>(
                    (double v1, double v2) => v1.Equals(v2),
                    (double v) => v.GetHashCode(),
                    (double v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "REAL"));

            var ishtibaq = runtimeEntityType.AddProperty(
                "Ishtibaq",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Ishtibaq", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Ishtibaq>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            ishtibaq.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                keyComparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                converter: new ValueConverter<ZonedDateTime, string>(
                    (ZonedDateTime x) => x.GetStringForDBColumn(),
                    (string x) => x.GetZonedDateTimeFromDBColumnString()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<ZonedDateTime, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<ZonedDateTime, string>(
                        (ZonedDateTime x) => x.GetStringForDBColumn(),
                        (string x) => x.GetZonedDateTimeFromDBColumnString())));
            ishtibaq.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var ishtibaqDegree = runtimeEntityType.AddProperty(
                "IshtibaqDegree",
                typeof(double),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("IshtibaqDegree", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<IshtibaqDegree>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);
            ishtibaqDegree.TypeMapping = DoubleTypeMapping.Default.Clone(
                comparer: new ValueComparer<double>(
                    (double v1, double v2) => v1.Equals(v2),
                    (double v) => v.GetHashCode(),
                    (double v) => v),
                keyComparer: new ValueComparer<double>(
                    (double v1, double v2) => v1.Equals(v2),
                    (double v) => v.GetHashCode(),
                    (double v) => v),
                providerValueComparer: new ValueComparer<double>(
                    (double v1, double v2) => v1.Equals(v2),
                    (double v) => v.GetHashCode(),
                    (double v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "REAL"));

            var latitude = runtimeEntityType.AddProperty(
                "Latitude",
                typeof(decimal),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Latitude", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Latitude>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            latitude.TypeMapping = SqliteDecimalTypeMapping.Default;

            var longitude = runtimeEntityType.AddProperty(
                "Longitude",
                typeof(decimal),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Longitude", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Longitude>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            longitude.TypeMapping = SqliteDecimalTypeMapping.Default;

            var maghrib = runtimeEntityType.AddProperty(
                "Maghrib",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Maghrib", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Maghrib>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            maghrib.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                keyComparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                converter: new ValueConverter<ZonedDateTime, string>(
                    (ZonedDateTime x) => x.GetStringForDBColumn(),
                    (string x) => x.GetZonedDateTimeFromDBColumnString()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<ZonedDateTime, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<ZonedDateTime, string>(
                        (ZonedDateTime x) => x.GetStringForDBColumn(),
                        (string x) => x.GetZonedDateTimeFromDBColumnString())));
            maghrib.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var nextFajr = runtimeEntityType.AddProperty(
                "NextFajr",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("NextFajr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<NextFajr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            nextFajr.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                keyComparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                converter: new ValueConverter<ZonedDateTime, string>(
                    (ZonedDateTime x) => x.GetStringForDBColumn(),
                    (string x) => x.GetZonedDateTimeFromDBColumnString()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<ZonedDateTime, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<ZonedDateTime, string>(
                        (ZonedDateTime x) => x.GetStringForDBColumn(),
                        (string x) => x.GetZonedDateTimeFromDBColumnString())));
            nextFajr.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var shuruq = runtimeEntityType.AddProperty(
                "Shuruq",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Shuruq", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Shuruq>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            shuruq.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                keyComparer: new ValueComparer<ZonedDateTime>(
                    (ZonedDateTime v1, ZonedDateTime v2) => v1.Equals(v2),
                    (ZonedDateTime v) => v.GetHashCode(),
                    (ZonedDateTime v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                converter: new ValueConverter<ZonedDateTime, string>(
                    (ZonedDateTime x) => x.GetStringForDBColumn(),
                    (string x) => x.GetZonedDateTimeFromDBColumnString()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<ZonedDateTime, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<ZonedDateTime, string>(
                        (ZonedDateTime x) => x.GetStringForDBColumn(),
                        (string x) => x.GetZonedDateTimeFromDBColumnString())));
            shuruq.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var key = runtimeEntityType.AddKey(
                new[] { iD });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "MuwaqqitPrayerTimes");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
