// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using PrayerTimeEngine.Core.Common.Extension;
using PrayerTimeEngine.Core.Domain.DynamicPrayerTimes.Providers.Muwaqqit.Models.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace PrayerTimeEngine.Core.Data.EntityFramework.Generated_CompiledModels
{
    [EntityFrameworkInternal]
    public partial class MuwaqqitDailyPrayerTimesEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "PrayerTimeEngine.Core.Domain.DynamicPrayerTimes.Providers.Muwaqqit.Models.Entities.MuwaqqitDailyPrayerTimes",
                typeof(MuwaqqitDailyPrayerTimes),
                baseEntityType,
                propertyCount: 20,
                keyCount: 1);

            var iD = runtimeEntityType.AddProperty(
                "ID",
                typeof(int),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("ID", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<ID>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);

            var asr = runtimeEntityType.AddProperty(
                "Asr",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Asr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Asr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            asr.SetValueConverter(new ValueConverter<ZonedDateTime, string>(
                string (ZonedDateTime x) => x.GetStringForDBColumn(),
                ZonedDateTime (string x) => x.GetZonedDateTimeFromDBColumnString()));
            asr.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var asrKaraha = runtimeEntityType.AddProperty(
                "AsrKaraha",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("AsrKaraha", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<AsrKaraha>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            asrKaraha.SetValueConverter(new ValueConverter<ZonedDateTime, string>(
                string (ZonedDateTime x) => x.GetStringForDBColumn(),
                ZonedDateTime (string x) => x.GetZonedDateTimeFromDBColumnString()));
            asrKaraha.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var asrKarahaDegree = runtimeEntityType.AddProperty(
                "AsrKarahaDegree",
                typeof(double),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("AsrKarahaDegree", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<AsrKarahaDegree>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);

            var asrMithlayn = runtimeEntityType.AddProperty(
                "AsrMithlayn",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("AsrMithlayn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<AsrMithlayn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            asrMithlayn.SetValueConverter(new ValueConverter<ZonedDateTime, string>(
                string (ZonedDateTime x) => x.GetStringForDBColumn(),
                ZonedDateTime (string x) => x.GetZonedDateTimeFromDBColumnString()));
            asrMithlayn.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var date = runtimeEntityType.AddProperty(
                "Date",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Date", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Date>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            date.SetValueConverter(new ValueConverter<ZonedDateTime, string>(
                string (ZonedDateTime x) => x.GetStringForDBColumn(),
                ZonedDateTime (string x) => x.GetZonedDateTimeFromDBColumnString()));
            date.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var dhuhr = runtimeEntityType.AddProperty(
                "Dhuhr",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Dhuhr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Dhuhr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            dhuhr.SetValueConverter(new ValueConverter<ZonedDateTime, string>(
                string (ZonedDateTime x) => x.GetStringForDBColumn(),
                ZonedDateTime (string x) => x.GetZonedDateTimeFromDBColumnString()));
            dhuhr.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var duha = runtimeEntityType.AddProperty(
                "Duha",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Duha", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Duha>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            duha.SetValueConverter(new ValueConverter<ZonedDateTime, string>(
                string (ZonedDateTime x) => x.GetStringForDBColumn(),
                ZonedDateTime (string x) => x.GetZonedDateTimeFromDBColumnString()));
            duha.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var fajr = runtimeEntityType.AddProperty(
                "Fajr",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Fajr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Fajr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            fajr.SetValueConverter(new ValueConverter<ZonedDateTime, string>(
                string (ZonedDateTime x) => x.GetStringForDBColumn(),
                ZonedDateTime (string x) => x.GetZonedDateTimeFromDBColumnString()));
            fajr.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var fajrDegree = runtimeEntityType.AddProperty(
                "FajrDegree",
                typeof(double),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("FajrDegree", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<FajrDegree>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);

            var insertInstant = runtimeEntityType.AddProperty(
                "InsertInstant",
                typeof(Instant?),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("InsertInstant", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<InsertInstant>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            insertInstant.SetValueConverter(new ValueConverter<Instant?, string>(
                string (Instant? x) => (x != null ? x.Value.GetStringForDBColumn() : null),
                Instant? (string x) => (x != null ? ((Instant? )(x.GetInstantFromDBColumnString())) : null)));

            var isha = runtimeEntityType.AddProperty(
                "Isha",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Isha", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Isha>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            isha.SetValueConverter(new ValueConverter<ZonedDateTime, string>(
                string (ZonedDateTime x) => x.GetStringForDBColumn(),
                ZonedDateTime (string x) => x.GetZonedDateTimeFromDBColumnString()));
            isha.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var ishaDegree = runtimeEntityType.AddProperty(
                "IshaDegree",
                typeof(double),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("IshaDegree", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<IshaDegree>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);

            var ishtibaq = runtimeEntityType.AddProperty(
                "Ishtibaq",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Ishtibaq", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Ishtibaq>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            ishtibaq.SetValueConverter(new ValueConverter<ZonedDateTime, string>(
                string (ZonedDateTime x) => x.GetStringForDBColumn(),
                ZonedDateTime (string x) => x.GetZonedDateTimeFromDBColumnString()));
            ishtibaq.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var ishtibaqDegree = runtimeEntityType.AddProperty(
                "IshtibaqDegree",
                typeof(double),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("IshtibaqDegree", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<IshtibaqDegree>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);

            var latitude = runtimeEntityType.AddProperty(
                "Latitude",
                typeof(decimal),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Latitude", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Latitude>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);

            var longitude = runtimeEntityType.AddProperty(
                "Longitude",
                typeof(decimal),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Longitude", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Longitude>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);

            var maghrib = runtimeEntityType.AddProperty(
                "Maghrib",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Maghrib", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Maghrib>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            maghrib.SetValueConverter(new ValueConverter<ZonedDateTime, string>(
                string (ZonedDateTime x) => x.GetStringForDBColumn(),
                ZonedDateTime (string x) => x.GetZonedDateTimeFromDBColumnString()));
            maghrib.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var nextFajr = runtimeEntityType.AddProperty(
                "NextFajr",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("NextFajr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<NextFajr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            nextFajr.SetValueConverter(new ValueConverter<ZonedDateTime, string>(
                string (ZonedDateTime x) => x.GetStringForDBColumn(),
                ZonedDateTime (string x) => x.GetZonedDateTimeFromDBColumnString()));
            nextFajr.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var shuruq = runtimeEntityType.AddProperty(
                "Shuruq",
                typeof(ZonedDateTime),
                propertyInfo: typeof(MuwaqqitDailyPrayerTimes).GetProperty("Shuruq", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuwaqqitDailyPrayerTimes).GetField("<Shuruq>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            shuruq.SetValueConverter(new ValueConverter<ZonedDateTime, string>(
                string (ZonedDateTime x) => x.GetStringForDBColumn(),
                ZonedDateTime (string x) => x.GetZonedDateTimeFromDBColumnString()));
            shuruq.SetSentinelFromProviderValue("0001-01-01T00:00:00 UTC (+00)");

            var key = runtimeEntityType.AddKey(
                new[] { iD });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "MuwaqqitPrayerTimes");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
